#
#	Makefile のターゲットシステム依存部（EZ-KIT Lite BF548用）
#

#
#  コンパイルオプション
#
INCLUDES := $(INCLUDES) -I$(CONFIGDIR)/$(CPU)/$(SYS)  -I$(SRCDIR)/config/$(CPU)/_common_bf548 \
			-I$(SRCDIR)/pdic/simple_sio
COPTS := $(COPTS)
LDFLAGS := $(LDFLAGS)

#
#  カーネルに関する定義
#
KERNEL_DIR := $(KERNEL_DIR):$(CONFIGDIR)/$(CPU)/$(SYS):$(SRCDIR)/config/$(CPU)/_common_bf548 \
				:$(SRCDIR)/pdic/simple_sio
KERNEL_ASMOBJS := $(KERNEL_ASMOBJS)
KERNEL_COBJS := $(KERNEL_COBJS) chip_config.o uart.o chip_debugboot.o chip_dump.o

#
#  リンカスクリプトの定義
#
LDSCRIPT = $(CPU)/_common_bf548/bf548elf.ld

