specVersion: 0.0.1
name: jsp_sh1-zunda_sh1
projects:
  - name: jsp_core
    source:
      type: git
      location: 'https://github.com/PizzaFactory/jsp_core.git'
components:
  - alias: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:next
  - alias: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - alias: pizza-dev
    type: dockerimage
    image: camino.azurecr.io/vintage-pizza/pf-gnuchains4x-sh-elf:4.7.4-20140603
    memoryLimit: 512Mi
    volumes:
    - containerPath: /projects
      name: projects
commands:
  - name: "build configurator"
    actions:
      - type: exec
        component: theia-dev
        command: cd ${CHE_PROJECTS_ROOT}/jsp_core/cfg && make CC=gcc-4.7 CXX=g++-4.7 && echo && echo Build complete.
  - name: "configure sample1"
    actions:
      - type: exec
        component: theia-dev
        command: cd ${CHE_PROJECTS_ROOT}/jsp_core && ./configure -C sh1 -S zunda_sh1
  - name: "make depend"
    actions:
      - type: exec
        component: theia-dev
        command: cd ${CHE_PROJECTS_ROOT}/jsp_core && make depend TARGET=sh-pizzafactory-elf && echo && echo Done.
  - name: "build JSP kernel"
    actions:
      - type: exec
        component: theia-dev
        command: cd ${CHE_PROJECTS_ROOT}/jsp_core && make TARGET=sh-pizzafactory-elf
